# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cardeditor.ui'
#
# Created: Wed Sep 24 22:03:07 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(640, 412)
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(0, -10, 641, 411))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.basicPage = QtGui.QWidget()
        self.basicPage.setObjectName(_fromUtf8("basicPage"))
        self.line = QtGui.QFrame(self.basicPage)
        self.line.setGeometry(QtCore.QRect(20, 320, 601, 21))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.basicPage)
        self.line_2.setGeometry(QtCore.QRect(440, 30, 21, 371))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.statusEdit = QtGui.QPlainTextEdit(self.basicPage)
        self.statusEdit.setGeometry(QtCore.QRect(20, 30, 411, 281))
        self.statusEdit.setObjectName(_fromUtf8("statusEdit"))
        self.userEdit = QtGui.QLineEdit(self.basicPage)
        self.userEdit.setGeometry(QtCore.QRect(20, 350, 411, 51))
        self.userEdit.setObjectName(_fromUtf8("userEdit"))
        self.advancedButton = QtGui.QPushButton(self.basicPage)
        self.advancedButton.setGeometry(QtCore.QRect(470, 30, 151, 41))
        self.advancedButton.setObjectName(_fromUtf8("advancedButton"))
        self.readButton = QtGui.QPushButton(self.basicPage)
        self.readButton.setGeometry(QtCore.QRect(470, 120, 151, 81))
        self.readButton.setObjectName(_fromUtf8("readButton"))
        self.writeButton = QtGui.QPushButton(self.basicPage)
        self.writeButton.setGeometry(QtCore.QRect(470, 230, 151, 81))
        self.writeButton.setObjectName(_fromUtf8("writeButton"))
        self.lookupButton = QtGui.QPushButton(self.basicPage)
        self.lookupButton.setGeometry(QtCore.QRect(470, 350, 151, 51))
        self.lookupButton.setObjectName(_fromUtf8("lookupButton"))
        self.stackedWidget.addWidget(self.basicPage)
        self.advancedPage = QtGui.QWidget()
        self.advancedPage.setObjectName(_fromUtf8("advancedPage"))
        self.basicButton = QtGui.QPushButton(self.advancedPage)
        self.basicButton.setGeometry(QtCore.QRect(470, 30, 151, 41))
        self.basicButton.setObjectName(_fromUtf8("basicButton"))
        self.userstatusEdit = QtGui.QPlainTextEdit(self.advancedPage)
        self.userstatusEdit.setGeometry(QtCore.QRect(20, 310, 411, 91))
        self.userstatusEdit.setReadOnly(True)
        self.userstatusEdit.setObjectName(_fromUtf8("userstatusEdit"))
        self.line_3 = QtGui.QFrame(self.advancedPage)
        self.line_3.setGeometry(QtCore.QRect(20, 290, 601, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.lookupEdit = QtGui.QLineEdit(self.advancedPage)
        self.lookupEdit.setGeometry(QtCore.QRect(470, 310, 151, 30))
        self.lookupEdit.setObjectName(_fromUtf8("lookupEdit"))
        self.lookupuserButton = QtGui.QPushButton(self.advancedPage)
        self.lookupuserButton.setGeometry(QtCore.QRect(470, 350, 151, 51))
        self.lookupuserButton.setObjectName(_fromUtf8("lookupuserButton"))
        self.statusEdit_2 = QtGui.QPlainTextEdit(self.advancedPage)
        self.statusEdit_2.setGeometry(QtCore.QRect(20, 70, 411, 161))
        self.statusEdit_2.setReadOnly(True)
        self.statusEdit_2.setObjectName(_fromUtf8("statusEdit_2"))
        self.line_4 = QtGui.QFrame(self.advancedPage)
        self.line_4.setGeometry(QtCore.QRect(440, 30, 20, 371))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.track1Edit = QtGui.QLineEdit(self.advancedPage)
        self.track1Edit.setGeometry(QtCore.QRect(20, 260, 131, 30))
        self.track1Edit.setObjectName(_fromUtf8("track1Edit"))
        self.track2Edit = QtGui.QLineEdit(self.advancedPage)
        self.track2Edit.setGeometry(QtCore.QRect(160, 260, 131, 30))
        self.track2Edit.setObjectName(_fromUtf8("track2Edit"))
        self.track3Edit = QtGui.QLineEdit(self.advancedPage)
        self.track3Edit.setGeometry(QtCore.QRect(300, 260, 131, 30))
        self.track3Edit.setObjectName(_fromUtf8("track3Edit"))
        self.label = QtGui.QLabel(self.advancedPage)
        self.label.setGeometry(QtCore.QRect(30, 240, 77, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.advancedPage)
        self.label_2.setGeometry(QtCore.QRect(170, 240, 77, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.advancedPage)
        self.label_3.setGeometry(QtCore.QRect(310, 240, 77, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.resetButton = QtGui.QPushButton(self.advancedPage)
        self.resetButton.setGeometry(QtCore.QRect(470, 80, 151, 41))
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.eraseButton = QtGui.QPushButton(self.advancedPage)
        self.eraseButton.setGeometry(QtCore.QRect(470, 130, 151, 41))
        self.eraseButton.setObjectName(_fromUtf8("eraseButton"))
        self.readtracksButton = QtGui.QPushButton(self.advancedPage)
        self.readtracksButton.setGeometry(QtCore.QRect(470, 180, 151, 51))
        self.readtracksButton.setObjectName(_fromUtf8("readtracksButton"))
        self.writetracksButton = QtGui.QPushButton(self.advancedPage)
        self.writetracksButton.setGeometry(QtCore.QRect(470, 240, 151, 51))
        self.writetracksButton.setObjectName(_fromUtf8("writetracksButton"))
        self.deviceEdit = QtGui.QLineEdit(self.advancedPage)
        self.deviceEdit.setGeometry(QtCore.QRect(20, 30, 271, 30))
        self.deviceEdit.setObjectName(_fromUtf8("deviceEdit"))
        self.deviceButton = QtGui.QPushButton(self.advancedPage)
        self.deviceButton.setGeometry(QtCore.QRect(310, 30, 121, 31))
        self.deviceButton.setObjectName(_fromUtf8("deviceButton"))
        self.stackedWidget.addWidget(self.advancedPage)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "CardEditor", None))
        self.advancedButton.setText(_translate("Dialog", "Advanced", None))
        self.readButton.setText(_translate("Dialog", "Read", None))
        self.writeButton.setText(_translate("Dialog", "Write", None))
        self.lookupButton.setText(_translate("Dialog", "Lookup", None))
        self.basicButton.setText(_translate("Dialog", "Basic", None))
        self.lookupuserButton.setText(_translate("Dialog", "Lookup User", None))
        self.label.setText(_translate("Dialog", "Track 1", None))
        self.label_2.setText(_translate("Dialog", "Track 2", None))
        self.label_3.setText(_translate("Dialog", "Track 3", None))
        self.resetButton.setText(_translate("Dialog", "Reset", None))
        self.eraseButton.setText(_translate("Dialog", "Erase", None))
        self.readtracksButton.setText(_translate("Dialog", "Read Tracks", None))
        self.writetracksButton.setText(_translate("Dialog", "Write Tracks", None))
        self.deviceButton.setText(_translate("Dialog", "Set Device", None))

